### ISSUE TITLE
Go to the beginning  of the document after scrolling

### ISSUE THREAD

**Issue by micos7** [escape-llc/pdf-component-vue#25]
I have a reset function 

```
const resetPage = () => {
    selectedPage.value = 1
    cacheStartPage.value = 1;
}
```
It doesnt work if a scroll down a while , and click - I suspect the `handleVisiblePages` eliminates the first page because of the rolling window type logic to save memory. How can I jump to the beginning manually without loading all the pages at all times?
I mainly use code from the scrolling Demo, single window continuous scrolling. Thanks for your work.

**Comment by escape-llc** [comment]
Firstly, thank you so much for trying this component!  Let me know if this answers your question.

By "scrolling demo" do you mean the "demo 1" or the "demo 4" page?  For now we'll assume you are using the "left panel" from the Faux Viewer demo (number 4) because it uses the Scroll Management feature.

Once the DOM is rendered, you can use "standard" techniques to bring elements into the viewport, using the DOM `id` of each page.  For example, if you scrolled down the viewport (to page 20), then want to "jump" to page 1 (or any) page's DOM element e.g. with `scrollIntoView` or document-hash, you can use the element's DOM `id` directly.

The page container DOM `id` is formed from the component's `id` plus `-page-n` where `n` is the 1-relative page number.  So if your component `id` prop is `my-pdf` then the DOM element for page 1 is `my-pdf-page-1`.

This still works with Scroll Management; when you instruct the viewport to scroll, you should get the `visible-pages` emit for that page (page 1) and then instruct `pageManagement` accordingly as the in the demo.  Also remember that Page Management uses 0-relative index and not 1-relative page (confusing, sorry).

We also thought about adding a `scrollIntoView` method to the component to make this kind of scrolling simpler so you don't need to compute element `id`s or access DOM elements (e.g. via `querySelector`).

We will try to get an example of this kind of functionality into one of the demo pages.

**Comment by micos7** [comment]
Solved it with scrollintoView -thanks again.

**Comment by escape-llc** [comment]
We are adding a new feature in `0.4.0` so you can invoke this without any extra code on your part.  See issue #26 for details.
