### ISSUE TITLE
High DPI, blurry rendering

### ISSUE THREAD

**Issue by MaxAntonsson** [escape-llc/pdf-component-vue#39]
Really appreciate the work you're doing here, it's a big improvement of previous pdfjs-adaptations for vue :+1:

I'm looking to fix blurry rendering on High DPI screens. Here's an example of what I mean:

This is a PDF rendered on a screen with `window.devicePixelRatio === 2`, before and after my attempt at a "fix":
![Screenshot 2023-12-05 at 11 13 40](https://github.com/escape-llc/pdf-component-vue/assets/50969647/91e3ab9d-e815-4766-a0f1-60b5e371367c)

This work in progress "fix" just includes inserting `window.devicePixelRatio` in a few places:
https://github.com/escape-llc/pdf-component-vue/compare/main...MaxAntonsson:pdf-component-vue:main

inspo from related pdfjs-issues:
- https://github.com/mozilla/pdf.js/issues/10509
- https://github.com/react-pdf-viewer/react-pdf-viewer/pull/1568/files

Got a sandbox reproduction/example here:
- https://stackblitz.com/edit/vitejs-vite-knk5gq

And the easiest way to test this is to open the "device inspector" in the browser and test with a responsive/mobile screen (can always check in console that `window.devicePixelRatio` > 1)

I'm basically looking for guidance here. Since I don't really got the full picture of your internal logic and maybe upcoming plans for the project going forward. Do you have any tips on where to implement this, to still support all `sizeModes` and avoid other potential bugs?

**Comment by escape-llc** [comment]
Thanks so much for the encouragement and the research!  We'll take a look at everything and get back with you.  Supporting high DPI is definitely desirable.  There are locations in `pdfjs` that take `dPR` into account, we should probably do the same.

Wrt to internal logic, we are not experts at `vuejs` and just empirically got to where we are now.  `console.log` ftw am I right!?  Other approaches did not leverage the built-in DOM reconciliation as we are.  Happy to have a discussion in the Discussions section.

Wrt upcoming plans for this project, we were just waiting for some interest to build up, and suggestions are welcomed.

**Comment by MaxAntonsson** [comment]
Great! Thanks for the quick feedback 🙌 If you prefer a discussion thread, feel free to close this 👍

**Comment by escape-llc** [comment]
Tried out the potential fix, and there are some issues with the "Resize" demo.  The timing of setting `canvas.style.xxx` is causing some jarring updates.  Going to keep looking into getting a better update sequence.

**Comment by escape-llc** [comment]
The whole hi-dpi thing amounts to:
* expand the `canvas` by the pixel ratio, e.g. 2.
* draw into the expanded `canvas` with `pdfjs`.
* rescale the `canvas` via CSS `width` and `height`.
  * on hi-dpi this is actually enough pixels to render correctly.

So we overlooked the fact that in this component, the sizing model is "outside-in" via CSS and the `canvas.style` is already managed by the CSS; see the complete examples in the demos for what is happening.  Setting it programmatically is actually fighting this, hence the issues in the resize demo.

With this said, it is then just a matter of making the `canvas` larger by the `dPR` and drawing into that larger space, and then the CSS you are supposed to use (e.g. `page-stack` in the examples) "down sizes" everything.

> Note: you **must** use the recommended CSS with this component, otherwise the layers will not "stack" or be sized correctly.  Please see the wiki and the demos in the repo for clarification.

**Comment by escape-llc** [comment]
So we looked at everything and there is no getting around "sizing" the `canvas` with CSS.  However, the way we are doing it is via CSS variables, so there is no "re-writing" of the `canvas.style` only the variables.

To handle the `dPR` we are using the technique of putting it into the `transform` property of the page rendering, instead of directly changing the `viewport` scale, as some other examples show.

There is still the issue of re-sizing in a smooth way, but we are going to look at that later.  This may be a simple matter of animating the `--scale-factor` CSS variable, which is what the `pdfjs` layers' CSS uses (if you have looked at it).

We also refactored the overall rendering process to use one call to `requestAnimationFrame` and to prepare everything in one event via `Promise.all` instead of doing them in sequence.

We looked at the demo pages on a Samsung phone with DPR of 4.1 and everything looked okay.

This is all coming out in `0.5.0`.  In the meantime, you can try the current branch (after it gets pushed).

**Comment by escape-llc** [comment]
If you are interested in previewing and giving some feedback, everything is on the main branch now.
