### ISSUE TITLE
Can't setup locally

### ISSUE THREAD

**Issue by markus-ebner** [escape-llc/pdf-component-vue#64]
Hi, thanks for the great contribution to open source. 

I wanted to explore your demos, but I couldn't start it right away with `npm i` and `npm run dev` and I couldn't find any information what to do. 

Following error appears in the dev console: 
<img width="817" alt="Bildschirmfoto 2024-05-08 um 16 10 49" src="https://github.com/escape-llc/pdf-component-vue/assets/22777161/e2cbfb0f-9f15-4a1e-9f38-8a3d5aeef8a2">

**Comment by escape-llc** [comment]
It appears that in `pdfjs` 4.2.x the `workerSrc` must now be a `string` and previously it allowed a `URL`.

If you change your setup to pass a string instead of URL it works.

In the repo's application `main.js` it would change to this:
``````
bundle_v4.pdfjs.GlobalWorkerOptions.workerSrc = new URL("pdfjs-dist/build/pdf.worker.min.mjs", import.meta.url).toString();
``````

This is technically not a work-around, but results from changes in `pdfjs` across versions.

We will make some documentation in the meantime to alert others, and updates to the app in the repo.
